# Generated by Django 4.1.7 on 2023-04-14 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_products_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
