# Generated by Django 4.1.7 on 2023-06-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_cart_ticket_checkout_cartitem_cart_items_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("not-paid", "Not Paid"),
                ],
                default="not-paid",
                max_length=10,
            ),
        ),
    ]
