# Generated by Django 4.1.7 on 2023-06-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_checkout_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
