# Generated by Django 4.1.7 on 2023-09-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
    ]
