# Generated by Django 4.1.7 on 2023-09-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_category_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default='/media/jordan.png', upload_to='stores/'),
        ),
    ]
