# Generated by Django 4.1.7 on 2023-09-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/media/default.png', upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(default='/media/default.png', upload_to='stores/'),
        ),
    ]
