# Generated by Django 4.1.7 on 2023-11-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_wishlistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
