# Generated by Django 4.1.7 on 2023-11-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/media/default.png', upload_to='store/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='/media/default.png', upload_to='store/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='/media/default.png', upload_to='store/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='/media/default.png', upload_to='store/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(default='/media/default.png', upload_to='store/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image6',
            field=models.ImageField(default='/media/default.png', upload_to='store/products/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
