# Generated by Django 4.1.7 on 2023-12-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_address'),
        ('store', '0020_image_remove_product_image_remove_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
    ]
