# Generated by Django 4.1.7 on 2023-12-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_address'),
        ('store', '0021_alter_checkout_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='checkout',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
    ]
