# Generated by Django 4.1.7 on 2024-04-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0024_alter_checkout_delivery_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="checkout",
            options={"ordering": ["-created"]},
        ),
    ]
