# Generated by Django 4.1.7 on 2024-05-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0025_wallet_alter_checkout_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="received",
            field=models.BooleanField(default=False),
        ),
    ]
