# Generated by Django 4.1.7 on 2024-06-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0027_cartitem_delivered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("not-paid", "Not Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="not-paid",
                max_length=10,
            ),
        ),
    ]
