# Generated by Django 4.1.7 on 2024-06-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_rename_name_bankdetail_account_name_and_more"),
        ("store", "0028_alter_checkout_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanceledCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cancel_reason", models.TextField()),
                ("canceled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canceled_checkout",
                        to="store.checkout",
                    ),
                ),
                (
                    "refund_bank_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payment.bankdetail",
                    ),
                ),
            ],
        ),
    ]
