# Generated by Django 4.1.7 on 2024-10-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_wishlistitem_options_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='default_image',
            field=models.URLField(default='https://example.com/default.png'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
