# Generated by Django 4.1.7 on 2024-06-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_bankdetail_alter_transaction_bank_details"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankdetail",
            old_name="name",
            new_name="account_name",
        ),
        migrations.AddField(
            model_name="bankdetail",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
