# Generated by Django 4.1.7 on 2023-04-29 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-id"], "verbose_name_plural": "Rooms"},
        ),
        migrations.AlterField(
            model_name="messages",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.room",
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
