# Generated by Django 4.1.7 on 2023-04-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_buyerprofile_user_alter_sellerprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerprofile",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
