# Generated by Django 4.1.7 on 2024-03-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="nin",
        ),
        migrations.AddField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
